New ways to handle

diff --git a/.github/workflows/rebase.yaml b/.github/workflows/rebase.yaml
--- a/.github/workflows/rebase.yaml
+++ b/.github/workflows/rebase.yaml
@@ -99,15 +99,23 @@ jobs:
 
             # Loop through all remote branches and find the closest merge base
             echo "Iterating through remote branches..."
-            for BRANCH in $(git for-each-ref --format '%(refname:short)' refs/remotes/origin); do
+            git for-each-ref --format='%(refname:short)' refs/remotes/origin | while read -r BRANCH; do
               echo "Checking branch: $BRANCH"
-              if [ "$BRANCH" != "origin/${{ matrix.branch }}" ]; then
+              if [ "$BRANCH" != "$TARGET_BRANCH" ]; then
+                # Check if either branch is 'develop' and handle accordingly
                 if [ "$BRANCH" = "origin/develop" ] || [ "$TARGET_BRANCH" = "refs/remotes/origin/develop" ]; then
                   echo "Special handling for 'develop' branch..."
-                  MERGE_BASE=$(git merge-base $TARGET_BRANCH origin/develop) || { echo "_--_Failed to find merge base with develop"; continue; }
+                  MERGE_BASE=$(git merge-base $TARGET_BRANCH refs/remotes/origin/develop) || { echo "Failed to find merge base with develop"; continue; }
                 else
                   echo "Calculating merge base between $TARGET_BRANCH and $BRANCH..."
-                  MERGE_BASE=$(git merge-base $TARGET_BRANCH $BRANCH) || { echo "Failed to find merge base with $BRANCH"; continue; }
+                  # Calculate merge base based on commit timestamps
+                  TIMESTAMP_TARGET=$(git log -1 --format="%ct" $TARGET_BRANCH)
+                  TIMESTAMP_BRANCH=$(git log -1 --format="%ct" $BRANCH)
+                  if [ "$TIMESTAMP_TARGET" -gt "$TIMESTAMP_BRANCH" ]; then
+                      MERGE_BASE=$(git log -1 --format="%H" $TARGET_BRANCH)
+                  else
+                      MERGE_BASE=$(git log -1 --format="%H" $BRANCH)
+                  fi
                 fi
 
                 # Check if the current branch is the closest match
